# Generated by Django 3.1.5 on 2021-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
