# Generated by Django 3.1.5 on 2021-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210525_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='ideal',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bmi',
            name='risk',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bmi',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
